### ISSUE TITLE
#Feature - Graveyard

### ISSUE THREAD

**Issue by Jonas-Wendland** [Braun-Johannes/Capstone-Project-BattlePets#10]
## Value Proposition

**As a** pet lover,

**I want to** see a list of deceased Pets in a graveyard,

**so that I** can see which pets i had and how long they survived.

## Description

![Bildschirmfoto 2024-06-07 um 15 05 31](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/164337027/baf31661-2ee6-4404-9cd3-5ae5e58cab75)

## Acceptance Criteria

-[ ] In the living room there is a button which on click opens the graveyard
- [ ] The page's headlin is "graveyard"
- [ ] It displays pet details including
  - [ ]`name`,
  - [ ]`emoji/Icon` (A representative emoji or dummy image/link that visually identifies the pet type or personality)
  - [ ] `Days Survived`
- [ ] underneath is the currentPet displayed with:
  - [ ] `name`
  - [ ] `Days Alive`
  - [ ] current `health`
- [ ] If there are no pets in the graveyard, the message `No animals in the graveyard yet. You are doing a great job!` should be shown.

## Tasks

- [ ] Create a feature branch `feature/graveyard`
- [ ] Create the page `Graveyard`
- [ ] Create a state to save the stats the Pet died.
- [ ] Create a list with `Cards` of deceased pets with
  - [ ] `name`
  - [ ] `lived`
- [ ]  Handle the case where there are no pets in the Graveyard
- [ ] Create a `Card` of the current Pet with:
  - [ ] `name`
  - [ ] `Days Alive`
  - [ ] `current `health`
- [ ]  There should be a `back` button that refers to the `Living room`
- [ ] Return the Headline `Graveyard` and the list of the deceased pets
