### ISSUE TITLE
MVP #6 - Time

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#11]
## Value Proposition

**As a** pet lover,

**I want to** be able to see the current pets age,

**so that I** can keep track of how long my pet has been alive.

## Description

![#6 - Time](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/164337027/9013c73e-3abb-431b-890e-c85d226b7798)

## Acceptance Criteria

- [ ] Implement "Time" status
    - [ ] The `satiety` lvl decreases over time (2 points every 30 minutes)
    - [ ] The `energy` lvl decreases over time (2 points every 30 minutes)
    - [ ] the `happiness` lvl decreases over time (2 points every 30 minutes)
- [ ] As soon as one of these stats is set to 0, the `health` lvl decreases over time (for every of the three parameters which is at zero health decreases 2 points every 30 minutes)
     - [ ] example: energy: 0, happiness: 0, satiety: 30    --------->    health decreases by 4 points every 30 minutes 
- [ ] The `Time` shows how long a pet is already alive
- [ ] When the health reaches 0, the pet is dead and the tombstone is displayed 

## Tasks
- [ ] Create feature branch `feature/time`
- [ ] create the properties "createdAt" and "updatedAt" which track when the pet was created and lastUpdated using
      a getCurrentTimeStamp function calling the current Date with Date.now( )
- [ ] when a pet is selected use useLocalStorage to save it in the localStorage
- [ ] use useEffect to calculate the pets health and save it to the localStorage each time the health changes
- [ ] use setInterval within useEffect to decrease the stats over time
