### ISSUE TITLE
MVP #5 - Interaction / LocalStorage

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#12]
## Value proposition

**As a** pet lover,

**I want to** interact with my pet,

**so that** I can fulfill my pets needs and it lives as long as possible.

## Description

![#5 - Interaction](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/164337027/00b32766-ffac-4e23-8c3f-31a3310d8634)

## Acceptance criteria

- [ ] Interactive Buttons
    - [ ] A "Sleep" interaction to increase the pets energy by 5 points.
    - [ ] A "Play" interaction, to increase the pets happiness by 5 points.
    - [ ] A "Feed" interaction,  to increase the pets food by 5 points.
- [ ] Clicking any of the buttons should result in immediate visual feedback on the pet's stats (`happiness`, `satiety`, `energy`), indicating the effect of each interaction.
- [ ] The pets information should persist between sessions
- [ ] Happiness, Energy and Satiety should never exceed the maximum value of 100 (of the value is at 98 and the button is clicked, the 
      value should jump to 100)

## Tasks

- [ ] Create feature branch `feature/interaction`
- [ ] use localStorage the make the selectedPet and the mode persist between sessions
- [ ] create a handleInteraction( ) to handle the increment in the pets stats
