### ISSUE TITLE
#Feature - SnackBar

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#17]
## Value Proposition

**As a** pet lover,

**I want to** receive pop-up notifications,

**so that I** will not miss important confirmations.

## Description

![image](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/123096081/87d3c5dc-4648-4727-9028-35cf4edd33dd)

## Acceptance Criteria

- [ ] Display a PopUp Message (confirmation) after:
    - [ ] selecting a starter pet
    - [ ] changing a pets name
- [ ] The displayed messages should only last up to 3/4 seconds
- [ ] The displayed snackbar message should include a button or be clickable to allow dismissal before 3 seconds
    
## Tasks

- [ ] create feature branch `feature/PopUpMessage`
- [ ] create a snackbar component
