### ISSUE TITLE
# Styling - Select

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#18]
## Value Proposition

**As a** pet lover,

**I want to** see images of the pet instead of just the type of pet,

**so that I** can have a nice visual experience of how my pet looks.

## Description

![Bildschirmfoto 2024-06-06 um 14 29 15](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/164337027/4fd37bb4-9ef8-412b-bfbb-7a067d4be9f0)

## Acceptance Criteria

- [ ] The starter pets are displayed with chosen svg images
- [ ] the selected pet is displayed with chosen svg images

## Tasks

- [ ] Add animal Icons
- [ ] write component to handle svg images
- [ ] Display them in the petlist at the Select page
- [ ] display the Selected Pet in the Livingroom
- [ ] add aria label for every icon
