### ISSUE TITLE
# Feature - Hall of Fame/ MongoDb

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#20]
## Value Proposition

As a pet lover,

I want to , compare the life time of my pet to other user's pets,

so that I can i have more competitive game experience.

## Description

![Image](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/123096081/f883b6b0-8036-4816-80e4-4b353f09d726)

![Image](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/123096081/5f6f19e6-364e-409b-9536-89e7a70914b5)

## Acceptance Criteria

- [ ] in the livingroom and in the graveyard, there is a button displayed which links to the hallOfFame page
- [ ] on the hallOfFame page the top 100 pets cards who lived the longest among all users are displayed
- [ ] only dead pets are included in the hall of fame
- [ ] the cards include:
    - [ ] the pets name
    - [ ] the pets icon
    - [ ] time alive
 - [ ] the pets are ranked (1-100)

## Tasks

- [ ] Create a feature branch `feature/hallOfFame`
- [ ] create a mongo db database
- [ ] write the api route for posting deceased pets to the database
- [ ] write the api route for fetching the top 100 pets concerning lifetime from the database
