### ISSUE TITLE
# Styling - Living room Icons

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#21]
## Value Proposition

**As a** pet lover,

**I want to**  see the buttons and stat types represented with icons,

**so that I** can have an easy understanding of their purpose.

## Description

![Bildschirmfoto 2024-06-06 um 14 38 16](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/164337027/c98dd4d4-dbc1-4042-b85c-75b2ed235143)

## Acceptance Criteria

- [ ] see icons in all the buttons
    - [ ] Interaction - edit - eliminate
- [ ] see icons as stat types

## Tasks

- [ ] Create feature branch `styling-livingRoom/Icons`
- [ ] replace the buttons text content with Icons
- [ ] replace the stat type text content with icons
- [ ] add aria label to every icon
