### ISSUE TITLE
#Styling Living Room Background

### ISSUE THREAD

**Issue by Jonas-Wendland** [Braun-Johannes/Capstone-Project-BattlePets#26]
## Value Proposition

**As a** pet lover,

**I want to** have a nice looking background,

**so that I**  can see my Pet in a nice Livingroom.

## Description

![#background](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/131983184/8052c904-bff1-4bf9-8b2b-834caf00fab2)

## Acceptance Criteria

- [ ] See a nice Background

## Tasks

- [ ] Create feature branch `feature/styling-livingRoom/Background`
- [ ] add a Image from the background
- [ ] show the Background in the Livingroom
