### ISSUE TITLE
# Styling - Icon implementation

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#28]
## Value Proposition

Implementation of chosen icons with own component

## Description

![#Styling - Icons](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/164337027/bf67437b-8154-4e5a-88f3-e34c99e5dbee)

## Acceptance Criteria

- [ ] Implementing Icon logic

## Tasks

- [ ] Create feature branch `styling/Icons`
- [ ] create an Icons Array
- [ ] Create a Icons component 
      - [ ] the component should render the Icons
