### ISSUE TITLE
# Styling - Background

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#29]
## Value Proposition

**As a** pet lover,

**I want to** have a nice looking background,

**so that I**  don't go blind from looking at a white screen.

## Description

![#Styled - Background](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/164337027/1e2be4df-fc41-4adf-9787-cd78227261c2)

## Acceptance Criteria

- [ ] Background images as shown implemented on
    - [ ] select mode
    - [ ] living room mode
    - [ ] tombstone mode

## Tasks

- [ ] Create feature branch `styling-select/Background`
- [ ] add a image for the background
