### ISSUE TITLE
#Styling - Tombstone

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#30]
## Value Proposition

**As a pet lover**,

**I want to** see a tombstone of my dead animal,

**so that I** can honor my pets death and see how long it survived.

## Description

![#Tombstone](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/164337027/c5d5170c-c08d-4a5d-abbe-ba3668903c8c)

## Acceptance Criteria

- [ ] See a Tombstone icon that still is clickable when the pet is dead
     - [ ] Text that says: "R.I.P - `petName`- "Time alive" - Select a new survival pet" 
 - [ ] The "TIME ALIVE" - should be the time the pet survived
 - [ ] The Tombstone is still clickable and opens the select mode

## Tasks

- [ ] Create feature branch `styling-tombstone/Icon`
- [ ] implement SVGIcon of tombstone
- [ ] pass pets time alive
