### ISSUE TITLE
# Usability - Smooth transition

### ISSUE THREAD

**Issue by niehaus-alexander** [Braun-Johannes/Capstone-Project-BattlePets#33]
## Value Proposition

As a pet lover,
I want to experience a smooth transition when exiting the pet selection process,
so that I can enjoy a seamless and enjoyable experience using the app.

## Acceptance Criteria

- [ ] when selecting a pet there should be a smooth transition into the living room

## Tasks

- [ ] Create a feature branch `feature/smooth transition`
- [ ] Use either css transition property or possibly an external library like "react-transition-group" to implement the transition logic
