### ISSUE TITLE
# Feature - Graveyard Detailspage

### ISSUE THREAD

**Issue by niehaus-alexander** [Braun-Johannes/Capstone-Project-BattlePets#38]
## Value Proposition

As a pet lover,

I want to be linked to a details page of my deceased pet,

so that I can remember the great times we spent together and indulge in memories.

## Description

![image](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/123096081/93ab9d12-b55b-46d5-93eb-468917f102c0)

## Acceptance Criteria

- [ ] clicking on one of the pets in the Graveyard links to the respective pets detailspage
- [ ] the detailspage includes:
             - [ ] pets image
             - [ ] time alive
             - [ ] adoption date
             - [ ] death date
             - [ ] a back button which links back to the graveyard
- [ ] the headline of the page displays the pets name
- [ ] below the headline the image of the pet is displayed

## Tasks

- [ ] Create a feature branch `feature/detailspage`
- [ ] use dynamic routing (slug, router id) to link to the deceased pets detailspage
