### ISSUE TITLE
# Feature - Filter Graveyard

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#39]
## Value Proposition

**As a** pet lover,

**I want to** be able to filter through my graveyard,

**so that I** can compare all my animals easily with each other.

## Description

![Bildschirmfoto 2024-06-07 um 15 05 59](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/164337027/6375913b-634a-4213-97e1-5c8be6cb1ec5)

## Acceptance Criteria

- [ ] button that displays "sort by" 
    - [ ] onClick opens a dropdown menu to select from:
        - [ ] Time alive (ascending)
        - [ ] Time alive (descending)
        - [ ] created at
        - [ ] type
        - [ ] name
- [ ] selecting one of the options sorts the graveyard pets 

## Tasks

- [ ] Create a feature branch `feature/filter-graveyard`
