### ISSUE TITLE
#Styling - colorful images for pets

### ISSUE THREAD

**Issue by niehaus-alexander** [Braun-Johannes/Capstone-Project-BattlePets#43]
## Value Proposition

**As a** pet lover,

**I want to** see colorful images of the pet,

**so that I** can have a nice visual experience of how my pet looks.

## Description

![Image](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/123096081/d3101f5f-2e2b-4b73-9cda-e7d06fd4a2bb)

## Acceptance Criteria

- [ ] The starter pets are displayed with their respective png images
- [ ] the selected pet is displayed with respective png image
- [ ] the deceased pets on the graveyard are being displayed with their respective png image
## Tasks

- [ ] create component png image
- [ ] add error handling to component
- [ ] create js file for images
- [ ] implement component in petlist, currentpet and graveyard
