### ISSUE TITLE
# Feature - Snackbar -  Stats reminder 

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#48]
## Value Proposition

**As a** pet lover,

**I want to** receive timely and actionable pop-up notifications when my pet's stats are low,

**so that I** can take prompt action to keep my pet alive and well.

## Description

![Bildschirmfoto 2024-06-12 um 10 50 50](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/164337027/c5065345-9ce8-42ff-987b-105a5cf85a96)

## Acceptance Criteria

- [ ] Display a PopUp Message when:
    - [ ] `energy`, `satiety`, `happiness` is below 40
    - [ ] `health` is below 50
- [ ] The displayed messages should only last up to 3/4 seconds
- [ ] The displayed message should include a button or be clickable to allow dismissal before 3 seconds
- [ ] When one of the 3 stats is pushed above 40 and drops afterwards again under 40 the message is displayed again
    
## Tasks

- [ ] create feature branch `feature/snackbar-reminder`
- [ ] add const `statThreshold` and `healthThreshold` to set point where message is displayed
- [ ] add state `[ snackShown, setSnackShown ]` to check for every stat if a message has been displayed already
- [ ] implement `useEffect` to:
    - [ ] check if stats are below the threshold
    - [ ] display message
    - [ ] toggles state that message has been shown
- [ ] add color scheme of stats and buttons to messages
