### ISSUE TITLE
# Feature - Add Soundtrack

### ISSUE THREAD

**Issue by niehaus-alexander** [Braun-Johannes/Capstone-Project-BattlePets#52]
## Value Proposition

As a pet lover,
I want to have background music playing within the app, 
so that my experience is more engaging and enjoyable.

## Description

Integrate the provided MP3 soundtrack into the Tamagotchi app to enhance the user experience. The soundtrack should play seamlessly in the background while the app is running.

## Acceptance Criteria

- [ ] The MP3 soundtrack should start playing automatically when the user opens the app.
- [ ] The music should loop continuously without interruptions.
- [ ] The volume of the music should be set at a moderate level by default
- [ ] Users should be able to adjust the volume of the soundtrack with a slider which is positioned in the top right corner of the living room page

## Tasks

- [ ] Create a feature branch `feature/soundtrack`
