### ISSUE TITLE
MVP #1 - Display 

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#6]
## Value proposition

**As a** pet lover,

**I want to** see the available pets,

**so that** I can choose my starter pet.

## Description

![Screenshot 2024-05-27 111004](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/131983184/c3d17994-bd35-4402-9869-dbf3c76d3e34)

## Acceptance criteria

- [ ] Add a headline "Select a SurvivalPet" to clearly indicate its purpose.
- [ ] Display the pets names from the `pets` array
    - [ ] The names should be displayed next to each other

## Tasks

- [ ] Create Array of Objects `pets`  / `pets.json`
     - [ ] Define a object structure for storing pet information (e.g., ID, name, type, age, etc.).

```javascript
const pets = [{id: "1", name: "Dieter", type: "Monkey" , health: 100, satiety: 100, happiness: 100, energy: 100}, ...]
```

- [ ] map over pets array to display its name
- [ ] each pet has a div

**Comment by ChristianMoschke** [comment]
LGTM! Acceptance criteria matched.

**Comment by miToe** [comment]
QA Done !
