### ISSUE TITLE
MVP #2 - Select

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#7]
## Value Proposition

**As a** pet lover,

**I want to** select a pet i want to play,

**so that I** can see my pet in the Living room with details.

## Description

![#2 - Select](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/164337027/20f006b7-2220-458c-8e1a-08bd3503cf56)

## Acceptance Criteria

- [ ] When a pets name is clicked, it should be highlighted
- [ ]  Below the SurvivalPet is a `form` which displays :
    - [ ] `name` default value
    - [ ]  A `Select` button
- [ ] Clicking the `Select` button submits the form and let you select the highlighted pet
- [ ] When a pet is selected the `Living room` with the selected pet should be displayed
    - [ ] A Headline that displays "Living room"
    - [ ] The pets `name` in the middle of the living room
    - [ ] Display the details of the chosen Pet in numbers
        - [ ] `Name` 
        - [ ] `Type` 
        - [ ] `Health` 
        - [ ] `Happiness`
        - [ ] `Satiety`
        - [ ] `Energy` 

## Tasks

- [x] Create feature branch `feature/select`
- [x] Create a PetForm Component below the PetList 
- [x] Create a selectedPet state which represents the currently clicked on pet
- [x] give the selectedPet a colored border to indicate its selection
- [x] Create a currentPet State and fill it with the data of the selected pet on submission of the form
- [x] create and display the CurrentPet component in the index.js
- [x] create a PetStats component
- [x] render PetStats within the CurrentPet component
- [x] use conditional rendering to render either the CurrentPet or the PetList/PetForm in the Living Room based on
whether there is a currentPet or not
