### ISSUE TITLE
MVP #3 - Edit

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#8]
## Value Proposition

**As a** pet lover,

**I want to** edit my pet,

**so that I** can give it a new name.

## Description

![Edit Wireframe](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/131983184/69eebb53-6379-4c01-a766-cc0662626af9)

## Acceptance Criteria

- [ ] A "Edit" button
    - [ ] in Edit Mode a `Cancel` button and a `Update Name` button are displayed
    - [ ] the `Cancel` button exits the Edit Mode
    - [ ] `Update Name` button updates the currentPets name and exits the editMode

## Tasks

- [ ] create feature branch `feature/edit`
- [ ] introduced `edit` to mode state
- [ ] toggle the editMode on clicking the edit Button
- [ ] Add EditForm 
    - [ ] reuse the PetForm Component to edit the `selectedPet` name in editMode
- [ ] clicking the Cancel Button exits the Edit Mode
- [ ] clicking update Name submits the PetForm, updates the pets name and exits editMode
