### ISSUE TITLE
MVP #4 - Delete

### ISSUE THREAD

**Issue by Braun-Johannes** [Braun-Johannes/Capstone-Project-BattlePets#9]
## Value Proposition

**As a** pet lover,

**I want to** be able to abandon my current pet,

**so that I** can play another pet.

## Description

![#4-Delete](https://github.com/Braun-Johannes/Capstone-Project-BattlePets/assets/164337027/64d96554-10bb-434f-aa30-1c41628af2ac)

## Acceptance Criteria

- [ ] A "Eliminate" `button` is displayed
- [ ] clicking toggles the `eliminateMode` which renders 2 Buttons
    - [ ] "Confirm", which `onClick` sets the `health` status to 0
    - [ ] "Cancel", which exits the `eliminateMode`
- [ ] When the `health` lvl drops to 0, the current pet will be "eliminated" 
- [ ] When a pet dies, a tombstone `button` with its `name` and a small text indicating its death are displayed
- [ ] When the tombstone `button` is clicked the "Select a Pet" is displayed again

## Tasks

- [ ] Create feature branch `feature/delete`
- [ ] create a Eliminate `button` and a `eliminateMode` state
- [ ] toggle the `eliminateMode` when the eliminate `button` is clicked
- [ ] when `eliminateMode` is on, display "Confirm" and "Cancel"
- [ ] "Cancel" sets the `eliminateMode` to "false"
- [ ] "Confirm" sets the currentPets `health` to 0 and then exits the `eliminateMode`
- [ ] when the currentPets `health` drops to 0 render a tombstone which `onClick` sets the currentPet to " " and disappears
